name: Lint Sketches

on:
  [pull_request, workflow_dispatch]

jobs:
  lint-sketches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint src
        uses: arduino/arduino-lint-action@v2
        with:
          path: LightAPRS-2-hab
          compliance: specification
          
